DROP DATABASE IF EXISTS UBending;
CREATE DATABASE UBending;
USE UBending;

DROP TABLE IF EXISTS Products;
CREATE TABLE Products (productID INTEGER AUTO_INCREMENT, owner INTEGER, name TINYTEXT, description MEDIUMTEXT, price INTEGER, state INTEGER, image LONGBLOB, idCategory INTEGER, PRIMARY KEY (productID));

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (userID INTEGER AUTO_INCREMENT, username TINYTEXT, password TINYTEXT, mail MEDIUMTEXT, location MEDIUMTEXT, userphoto LONGBLOB, PRIMARY KEY (userID));

DROP TABLE IF EXISTS ProductsFollowing;
CREATE TABLE ProductsFollowing (productID INTEGER, userID INTEGER);

DROP TABLE IF EXISTS Category;
CREATE TABLE IF NOT EXISTS Category (categoryID INTEGER AUTO_INCREMENT, name TINYTEXT, PRIMARY KEY (categoryID));

INSERT INTO Category (name) VALUES ("Cars");
INSERT INTO Category (name) VALUES ("Bikes");
INSERT INTO Category (name) VALUES ("Home");
