DROP DATABASE IF EXISTS UBending;
CREATE DATABASE UBending;
USE UBending;
DROP TABLE IF EXISTS Products;
CREATE TABLE  Products (productID INTEGER AUTO_INCREMENT, owner INTEGER, name VARCHAR(255), description VARCHAR(255), price INTEGER, location VARCHAR(255), state INTEGER, image LONGBLOB, idCategory INTEGER, PRIMARY KEY (productID));
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (userID INTEGER AUTO_INCREMENT, username VARCHAR(255), password VARCHAR(255), mail VARCHAR(255), location VARCHAR(255), userphoto LONGBLOB, PRIMARY KEY (userID));
DROP TABLE IF EXISTS ProductsFollowing;
CREATE TABLE ProductsFollowing (productID INTEGER, userID INTEGER);
DROP TABLE IF EXISTS Category;
CREATE TABLE IF NOT EXISTS Category (categoryID INTEGER AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (categoryID));

INSERT INTO Category (name) VALUES ("Cars");
INSERT INTO Category (name) VALUES ("Bikes");
INSERT INTO Category (name) VALUES ("Home");
